Repository FACK1/GBMQ, pull requests merged in 2019-04, with the labels that each got.

#66 Sign up
  package-lock.json
  package.json
  src/controllers/Student.controller.js
  src/router.js
Labels: in-review

#70 Readme how to use
  README.md
Labels: in-review

#64 Create models
  package-lock.json
  package.json
  src/models/Admin.model.js
  src/models/Choice.model.js
  src/models/Mark.model.js
  src/models/Question.model.js
  src/models/Quiz1Mark.model.js
  src/models/Quiz2Mark.model.js
  src/models/Student.model.js
  src/models/StudentsChoice.model.js
  src/models/index.js
  src/models/sequelize.js
Labels: in-review, technical

#69 Login back-end
  package-lock.json
  package.json
  src/controllers/Auth.controller.js
  src/controllers/Student.controller.js
  src/models/Student.model.js
  src/router.js
Labels: in-review

#71 Add a new student
  student/package-lock.json
  student/package.json
  student/src/components/Pages/Signup/index.js
Labels: awaiting-review

#76 Home authentication checking (Student State)
  student/src/components/Pages/Home/index.js
Labels: awaiting-review

#80 front-end path names
  student/src/App.js
Labels: awaiting-review

#79 Login user (post)
  student/src/components/Pages/Login/index.js
Labels: awaiting-review

#82 create question query #81
  src/controllers/Question.controller.js
Labels: awaiting-review

#84 Build the createChoice query
  src/controllers/Choice.controller.js
Labels: awaiting-review, technical

#85 Check auth endpoint
  package-lock.json
  package.json
  src/app.js
  src/controllers/Student.controller.js
  src/middlewares/checkStudentAuth.middleware.js
  src/router.js
  src/server.js
Labels: awaiting-review, technical

#97 Add Question By Admin
  src/controllers/Admin.controller.js
  src/router.js
Labels: Back end, awaiting-review

#99 Activities model
  src/models/Activity.model.js
  src/models/index.js
Labels: Back end, awaiting-review, technical

#96 Update scripts
  package.json
Labels: Back end, awaiting-review, chore, technical

#100 Home authentication on frontend
  src/controllers/Student.controller.js
  src/models/Admin.model.js
  src/models/Choice.model.js
  src/models/Question.model.js
  src/models/Student.model.js
  student/src/components/Pages/Home/index.js
  student/src/components/Pages/Home/index.style.js
Labels: Front end, in-review

#101 Home authentication Fix
  student/src/components/Pages/Home/index.js
Labels: Back end, bug

#102 Get quiz questions
  src/controllers/Quiz.controller.js
  src/router.js
Labels: Back end, awaiting-review, technical

#103 Get question by id (with choices)
  src/controllers/Choice.controller.js
  src/controllers/Question.controller.js
  src/models/index.js
  src/router.js
Labels: Back end, awaiting-review, technical

#104 Post student quiz endpoint
  src/controllers/Quiz.controller.js
  src/middlewares/checkStudentAuth.middleware.js
  src/router.js
Labels: Back end, awaiting-review, technical

#110 Get Student Mark
  src/controllers/Result.controller.js
  src/router.js
Labels: Back end, awaiting-review, technical

#109 Quiz request
  src/controllers/Quiz.controller.js
  student/src/App.js
  student/src/components/ChoicesList/index.js
  student/src/components/Pages/Start/index.js
  student/src/components/Question/index.js
  student/src/components/Quiz/index.js
Labels: Front end, in-progress, technical

#117 Signup button
  student/src/components/Form/index.style.js
  student/src/components/Pages/Login/index.js
  student/src/components/Pages/Login/index.style.js
Labels: awaiting-review, bug, technical

#118 Get quiz by id
  src/controllers/Quiz.controller.js
  src/router.js
  student/src/components/Quiz/index.js
Labels: Back end, Front end, bug, technical

#119 Get student result
  src/controllers/Result.controller.js
  student/src/components/Pages/Result/index.js
Labels: Front end, awaiting-review, technical

#121 Quiz questions number
  student/src/components/Question/index.js
  student/src/components/Quiz/index.js
Labels: Front end, awaiting-review, bug, technical

#129 Do Quiz2
  student/src/App.js
  student/src/components/Pages/Home/index.js
Labels: awaiting-review

#130 Comparison Page - BE
  src/controllers/Comparison.controller.js
  src/router.js
  student/src/components/Pages/Comparison/index.js
Labels: Back end, awaiting-review, technical

#131 Comparison Page - FE
  student/src/components/Pages/Comparison/index.js
Labels: Front end, awaiting-review, technical

#132 Get activities (Endpoint)
  package.json
  src/controllers/Activity.controller.js
  src/controllers/Quiz.controller.js
  src/controllers/Student.controller.js
  src/models/Activity.model.js
  src/models/Quiz1Mark.model.js
  src/models/Quiz2Mark.model.js
  src/router.js
Labels: Back end, awaiting-review, technical

#134 Get activities by request
  student/src/components/Pages/Activities/index.js
Labels: awaiting-review

#137 Post Quiz 2
  src/controllers/Question.controller.js
  src/controllers/Quiz.controller.js
  student/src/components/Choice/index.js
  student/src/components/ChoicesList/index.js
  student/src/components/Question/index.js
  student/src/components/Quiz/index.js
Labels: Front end, awaiting-review

#139 Quiz2 button disable/remaining
  src/controllers/Student.controller.js
  student/src/components/Pages/Home/index.js
  student/src/components/Pages/Home/index.style.js
  student/src/components/Quiz/index.js
Labels: Back end, Front end, bug, in-review, technical

#126 Validation for signup page
  src/controllers/Auth.controller.js
  src/models/Student.model.js
Labels: Back end, in-review, technical

#141 Update Design - mobile responsive
  student/src/components/Button/index.style.js
  student/src/components/Choice/index.style.js
  student/src/components/ChoicesList/index.style.js
  student/src/components/Form/index.style.js
  student/src/components/Pages/Home/index.style.js
  student/src/components/Pages/Login/b.png
  student/src/components/Pages/Login/bg.png
  student/src/components/Pages/Login/index.js
  student/src/components/Pages/Login/index.style.js
  student/src/components/Pages/Login/login-bg.png
  student/src/components/Question/index.style.js
Labels: Component, Front end, awaiting-review, bug

#142 Logout buttons
  student/package-lock.json
  student/package.json
  student/src/components/Pages/Comparison/index.js
  student/src/components/Pages/Home/index.js
  student/src/components/Pages/Home/index.style.js
  student/src/components/Pages/Start/index.js
  student/src/components/Pages/Start/index.style.js
Labels: Front end, awaiting-review, bug, technical

#146 Enable first day directly after quiz-1 finished
  src/controllers/Activity.controller.js
Labels: Back end, awaiting-review, bug

#145 Add the app hosted on heroku to readme
  README.md
Labels: awaiting-review

#144 Routing bugs
  package-lock.json
  src/controllers/Comparison.controller.js
  src/controllers/Result.controller.js
  src/middlewares/checkStudentAuth.middleware.js
  student/package-lock.json
  student/src/components/Pages/Comparison/index.js
  student/src/components/Pages/Result/index.js
  student/src/components/Quiz/index.js
Labels: Back end, Front end, awaiting-review, bug, technical

#152 Result Component - Bug
  student/src/components/Pages/Result/index.js
Labels: Front end, awaiting-review, bug, technical

#150 Admin App
  admin/.env
  admin/.gitignore
  admin/package-lock.json
  admin/package.json
  admin/public/index.html
  admin/public/manifest.json
  admin/src/App.css
  admin/src/App.js
  admin/src/App.test.js
  admin/src/index.css
  admin/src/index.js
  admin/src/logo.svg
  admin/src/serviceWorker.js
Labels: Front end, awaiting-review, technical

#154 Admin on heroku
  admin/package.json
  package.json
  src/app.js
  src/controllers/Student.controller.js
  src/router.js
Labels: Front end, awaiting-review, technical

#155 Admin app backend
  admin/package-lock.json
  admin/package.json
  package-lock.json
  package.json
  src/controllers/Admin.controller.js
  src/models/StudentsView.model.js
  src/models/index.js
  src/router.js
  src/server.js
Labels: Back end, enhancement

#160 Signup age field - add label
  student/src/components/Form/index.js
  student/src/components/Form/index.style.js
  student/src/components/Pages/Signup/index.js
Labels: Front end, awaiting-review

#158 Admin Login - Back end
  package-lock.json
  src/controllers/Admin.controller.js
  src/controllers/Auth.controller.js
  src/router.js
Labels: Back end, in-review

#161 Update scripts to add admin app build and dev start scripts #62
  package.json
Labels: Back end, awaiting-review

#162 Admin login - Front end
  admin/package-lock.json
  admin/package.json
  admin/public/index.html
  admin/src/App.js
  admin/src/components/AdminLogin/bg.png
  admin/src/components/AdminLogin/index.js
  admin/src/components/AdminLogin/index.style.js
  admin/src/components/Field/index.js
  admin/src/components/Field/index.style.js
  package-lock.json
Labels: Front end, awaiting-review, technical

#163 Admin check auth Middleware
  package-lock.json
  src/controllers/Auth.controller.js
  src/middlewares/checkAdminAuth.middleware.js
  src/router.js
Labels: Back end, awaiting-review, technical

#167 Download students sheets
  admin/src/components/StudentSheets/index.js
  admin/src/components/StudentSheets/index.style.js
Labels: Front end, awaiting-review, technical

#168 Login request
  admin/public/index.html
  admin/src/App.js
  admin/src/App.style.js
  admin/src/components/AdminLogin/index.js
  admin/src/components/StudentSheets/index.js
  src/controllers/Admin.controller.js
  src/controllers/Auth.controller.js
  src/router.js
Labels: Back end, Component, Front end, awaiting-review

#170 Add logout button
  admin/package-lock.json
  admin/package.json
  admin/src/App.js
  admin/src/components/StudentSheets/index.js
  admin/src/components/StudentSheets/index.style.js
  student/public/index.html
Labels: Front end, awaiting-review

#171 Validate quiz submisstion
  src/controllers/Activity.controller.js
  src/middlewares/checkQ1Availability.middleware.js
  src/router.js
  src/validations/quizChoices.validation.js
  student/src/components/Quiz/index.js
Labels: Back end, awaiting-review, bug
