Repository FACK1/GBMQ, pull requests merged in 2019-03, with the labels that each got.

#33 File structure - Frontend
  student/.babelrc
  student/.eslintrc.json
  student/.gitignore
  student/package-lock.json
  student/package.json
  student/public/index.html
  student/src/App.css
  student/src/App.js
  student/src/components/Button/index.js
  student/src/components/Button/index.style.js
  student/src/components/Choice/index.js
  student/src/components/Choice/index.style.js
  student/src/components/Form/index.js
  student/src/components/Form/index.style.js
  student/src/components/Image/index.js
  student/src/components/Image/index.style.js
  student/src/components/Pages/Activities/index.js
  student/src/components/Pages/Activities/index.style.js
  student/src/components/Pages/Comparison/index.js
  student/src/components/Pages/Comparison/index.style.js
  student/src/components/Pages/Home/index.js
  student/src/components/Pages/Home/index.style.js
  student/src/components/Pages/Login/index.js
  student/src/components/Pages/Login/index.style.js
  student/src/components/Pages/Result/index.js
  student/src/components/Pages/Result/index.style.js
  student/src/components/Pages/Signup/index.js
  student/src/components/Pages/Signup/index.style.js
  student/src/components/Pages/Start/index.js
  student/src/components/Pages/Start/index.style.js
  student/src/components/Question/index.js
  student/src/components/Question/index.style.js
  student/src/components/Quiz/index.js
  student/src/components/Quiz/index.style.js
  student/src/index.css
  student/src/index.js
Labels: in-review

#32 File structure - Backend
  .eslintrc.json
  .gitignore
  config.env
  package-lock.json
  package.json
  src/app.js
  src/controllers/Admin.controller.js
  src/controllers/Auth.controller.js
  src/controllers/Choice.controller.js
  src/controllers/Question.controller.js
  src/controllers/Quiz.controller.js
  src/controllers/Student.controller.js
  src/controllers/index.js
  src/middlewares/checkAdminAuth.middleware.js
  src/middlewares/checkStudentAuth.middleware.js
  src/middlewares/index.js
  src/models/Admin.model.js
  src/models/Choice.model.js
  src/models/Mark.model.js
  src/models/Question.model.js
  src/models/Student.model.js
  src/models/StudentsChoice.model.js
  src/models/index.js
  src/models/sequelize.js
  src/router.js
  src/server.js
  src/validations/index.js
  src/validations/login.validation.js
  src/validations/signup.validation.js
  student/.env
  student/package-lock.json
  student/package.json
  student/public/index.html
  travis.yml
Labels: in-review

#42 Question component
  public/images/questions/question1.jpg
  src/app.js
  student/public/index.html
  student/src/components/Choice/index.js
  student/src/components/Choice/index.style.js
  student/src/components/ChoicesList/index.js
  student/src/components/ChoicesList/index.style.js
  student/src/components/Image/index.js
  student/src/components/Image/index.style.js
  student/src/components/Question/index.js
  student/src/components/Question/index.style.js
  student/src/components/Question/questionNoImg.png
  student/src/components/Quiz/index.js
Labels: awaiting-review

#41 Form component
  package.json
  src/router.js
  student/package-lock.json
  student/package.json
  student/public/index.html
  student/src/App.css
  student/src/App.js
  student/src/components/Button/index.js
  student/src/components/Button/index.style.js
  student/src/components/ChoicesList/index.js
  student/src/components/ChoicesList/index.style.js
  student/src/components/Form/index.js
  student/src/components/Form/index.style.js
  student/src/components/Image/index.js
  student/src/components/Question/index.js
  student/src/components/Quiz/index.js
Labels: in-review

#46 Build react router #45
  student/package-lock.json
  student/package.json
  student/src/App.js
Labels: awaiting-review

#47 Login Page
  student/src/App.js
  student/src/components/Button/index.style.js
  student/src/components/Form/index.js
  student/src/components/Form/index.style.js
  student/src/components/Pages/Login/index.js
  student/src/components/Pages/Login/index.style.js
  student/src/components/Pages/Login/login-bg.png
Labels: awaiting-review

#49 Signup Page
  student/package-lock.json
  student/src/App.js
  student/src/components/Form/index.style.js
  student/src/components/Pages/Signup/index.js
  student/src/components/Pages/Signup/index.style.js
  student/src/components/Pages/Signup/signup-bg.png
Labels: in-review

#48 Quiz component
  student/package-lock.json
  student/src/App.js
  student/src/components/Choice/index.style.js
  student/src/components/Question/index.js
  student/src/components/Question/index.style.js
  student/src/components/Quiz/index.js
Labels: in-review

#53 Fix Form component
  src/app.js
  student/src/components/Form/index.js
  student/src/components/Form/index.style.js
  student/src/components/Pages/Login/index.js
  student/src/components/Pages/Signup/index.js
  student/src/components/Pages/Signup/index.style.js
  student/src/components/Question/index.js
Labels: bug, in-review

#54 Start Page
  student/src/App.js
  student/src/components/Pages/Start/index.js
  student/src/components/Pages/Start/index.style.js
  student/src/components/Pages/Start/start-bg.png
  student/src/components/Pages/Start/start-img.png
Labels: in-review

#55 Display default radio button #50
  student/src/components/Form/index.js
Labels: in-review

#56 Home page
  student/src/App.js
  student/src/components/Pages/Home/home-bg.png
  student/src/components/Pages/Home/home-img.png
  student/src/components/Pages/Home/index.js
  student/src/components/Pages/Home/index.style.js
Labels: in-review

#57 Activity Popup
  student/src/App.js
  student/src/components/Pages/Activities/index.js
  student/src/components/Pages/Activities/index.style.js
  student/src/components/Pages/Home/index.js
  student/src/components/Pages/Home/index.style.js
Labels: awaiting-review

#58 Comparison Page
  student/src/App.js
  student/src/components/Pages/Comparison/congratulations.png
  student/src/components/Pages/Comparison/index.js
  student/src/components/Pages/Comparison/index.style.js
Labels: in-review

#61 Build Student Model
  src/models/Student.model.js
Labels: awaiting-review

#67 make username unique
  src/models/Student.model.js
Labels: in-review
